# This workflow will:
# 1. Build and test the .NET project
# 2. Deploy it to Fly.io if current branch is "main"
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: 'REST API: Test and deploy to Fly.io'
on: [push, pull_request]

jobs:
  Test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --no-restore
      
    - name: Test
      run: dotnet test --no-build --verbosity normal

  Deploy:
    runs-on: ubuntu-latest
    needs: [Test]
    if: github.ref == 'refs/heads/main'

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true

    - name: Setup Fly.io CLI
      uses: superfly/flyctl-actions/setup-flyctl@master
      with:
        version: 0.0.478

    - name: Deploy to Fly.io 
      run: flyctl deploy --remote-only
      env:
        FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}